Eddited my special feature page.
EagleNationNews/EagleNationNews.github.io pull request #60
Opened 2018-05-10 14:37 UTC by hatcher307299

2018-05-10 19:17 UTC, EagleNationNews requested changes
Your paragraph tag is not in a column. It is placed inside a row, but not inside the column. Please revise.

2018-05-11 14:41 UTC, Briana304913 submitted a review, later dismissed
Approved

2018-05-15 13:49 UTC, Michelle367205 approved these changes
looks good dude

2018-05-15 13:52 UTC, Briana304913 approved these changes
Approved

2018-05-21 13:55 UTC, closed without merging